routes/frontend.php
<?php
use Illuminate\Support\Facades\Route;

Route::name('frontend.')->group(function () {

    Route::group(
        [

            'namespace' => 'Frontend'
        ],
        function () {
            Route::get('/', 'HomeController@index')->name('welcome');

            // Route::get('/', function () {
            //     return view('welcome');
            // });

            // Berita
            Route::resource('/berita', 'BeritaController');
            Route::get('/berita', 'BeritaController@home')->name('berita');
            Route::get('/show-berita/{berita}', 'BeritaController@show')->name('show-berita');
            Route::get('/berita/search', 'BeritaController@search')->name('berita-search');

            // Akademik
            Route::get('/ekstra', 'EkstraController@home')->name('ekstra');
            Route::get('/show-ekstra/{ekstra}', 'EkstraController@show')->name('show-ekstra');
            Route::get('/akreditasi', 'AkreditasiController@home')->name('akreditasi');
            Route::get('/beasiswa', 'BeasiswaController@home')->name('beasiswa');
            Route::get('/kegiatan-penunjang', 'KegiatanPenunjangController@home')->name('kegiatan-penunjang');

            // Profile
            Route::get('/galeri', 'GaleriController@home')->name('galeri');
            Route::get('/kurikulum', 'KurikulumController@home')->name('kurikulum');
            Route::get('/staf', 'StaffController@home')->name('staf');
            Route::get('/tentang', 'TentangController@home')->name('tentang');
            Route::get('/visi', 'VisiController@home')->name('visi');

            //Comment 
            Route::resource('/comment', 'CommentController');
            // Route::post('/berita/{comment}/comment', 'CommentController@store')->name('berita-comment');

            //Info PPDB
            Route::get('/info', 'InfoController@index')->name('info');

            //Daftar PPDB
            Route::resource('/daftar', 'DaftarController');
            Route::get('/success', 'DaftarController@success')->name('success');

            //Kontak
            Route::get('/kontak', 'HomeController@kontak')->name('kontak');
            // Route::get('/kontak', 'PesanController@create')->name('kontak');
            // Route::resource('pesan', 'PesanController');

            //Alumni
            Route::get('/alumni', 'HomeController@alumni')->name('alumni');

            //prestasi
            Route::get('/prestasi', 'HomeController@prestasi')->name('prestasi');
            Route::get('/show-prestasi/{prestasi}', 'PrestasiController@show')->name('show-prestasi');
        }

    );
});

Route::name('frontend.')->group(function () {
    Route::group([
        'namespace' => 'Frontend',
        'middleware' => 'auth'
    ], function () {
        Route::get('/admin', 'AdminController@index')->name('admin');

            Route::get('/berita-admin/{berita}/delete', 'BeritaController@destroy')->name('berita.delete');
            Route::get('/berita-admin/{berita}/edit', 'BeritaController@edit')->name('berita.edit');
            Route::patch('/berita-admin/{berita}', 'BeritaController@update')->name('berita.update');
            Route::resource('/berita-admin', 'BeritaController');

            Route::get('/galeri-admin/{galeri}/delete', 'GaleriController@destroy')->name('galeri.delete');
            Route::get('/galeri-admin/{galeri}/edit', 'GaleriController@edit')->name('galeri.edit');
            Route::patch('/galeri-admin/{galeri}', 'GaleriController@update')->name('galeri.update');
            Route::resource('/galeri-admin', 'GaleriController');

            Route::get('/staff-admin/{staff}/edit', 'StaffController@edit')->name('staff.edit');
            Route::patch('/staff-admin/{staff}', 'StaffController@update')->name('staff.update');
            Route::get('/staff-admin/{staff}/delete', 'StaffController@destroy')->name('staff.delete');
            Route::resource('/staff-admin', 'StaffController');

            Route::get('/daftar-admin', 'DaftarController@admin')->name('daftar.admin');

            Route::get('/kontak-admin/{kontak}/edit', 'KontakController@edit')->name('kontak.edit');
            Route::patch('/kontak-admin/{kontak}', 'KontakController@update')->name('kontak.update');
            Route::resource('/kontak-admin', 'KontakController');

            Route::get('/prestasi-admin/{prestasi}/edit', 'PrestasiController@edit')->name('prestasi.edit');
            Route::patch('/prestasi-admin/{prestasi}', 'PrestasiController@update')->name('prestasi.update');
            Route::get('/prestasi-admin/{prestasi}/delete', 'PrestasiController@destroy')->name('prestasi.delete');
            Route::resource('/prestasi-admin', 'PrestasiController');
            
            Route::get('/alumni-admin/{alumni}/edit', 'AlumniController@edit')->name('alumni.edit');
            Route::patch('/alumni-admin/{alumni}', 'AlumniController@update')->name('alumni.update');
            Route::get('/alumni-admin/{alumni}/delete', 'AlumniController@destroy')->name('alumni.delete');
            Route::resource('alumni-admin', 'AlumniController');

            Route::get('/tentang-admin/{tentang}/edit', 'TentangController@edit')->name('tentang.edit');
            Route::patch('/tentang-admin/{tentang}', 'TentangController@update')->name('tentang.update');
            Route::resource('tentang-admin', 'TentangController');

            Route::get('/karakter-admin/{karakter}/edit', 'KarakterController@edit')->name('karakter.edit');
            Route::patch('/karakter-admin/{karakter}', 'KarakterController@update')->name('karakter.update');
            Route::get('/karakter-admin/{karakter}/delete', 'KarakterController@destroy')->name('karakter.delete');
            Route::resource('karakter-admin', 'KarakterController');

            Route::get('/visi-admin/{visi}/edit', 'VisiController@edit')->name('visi.edit');
            Route::patch('/visi-admin/{visi}', 'VisiController@update')->name('visi.update');
            Route::resource('visi-admin', 'VisiController');

            Route::get('/akreditasi-admin/{akreditasi}/edit', 'AkreditasiController@edit')->name('akreditasi.edit');
            Route::patch('/akreditasi-admin/{akreditasi}', 'AkreditasiController@update')->name('akreditasi.update');
            Route::resource('akreditasi-admin', 'AkreditasiController');

            Route::get('/beasiswa-admin/{beasiswa}/edit', 'BeasiswaController@edit')->name('beasiswa.edit');
            Route::patch('/beasiswa-admin/{beasiswa}', 'BeasiswaController@update')->name('beasiswa.update');
            Route::get('/beasiswa-admin/{beasiswa}/delete', 'BeasiswaController@destroy')->name('beasiswa.delete');
            Route::resource('beasiswa-admin', 'BeasiswaController');

            Route::get('/kurikulum-admin/{kurikulum}/edit', 'KurikulumController@edit')->name('kurikulum.edit');
            Route::patch('/kurikulum-admin/{kurikulum}', 'KurikulumController@update')->name('kurikulum.update');
            Route::resource('/kurikulum-admin', 'KurikulumController');

            Route::get('/ekstra-admin/{ekstra}/edit', 'EkstraController@edit')->name('ekstra.edit');
            Route::patch('/ekstra-admin/{ekstra}', 'EkstraController@update')->name('ekstra.update');
            Route::get('/ekstra-admin/{ekstra}/delete', 'EkstraController@destroy')->name('ekstra.delete');
            Route::resource('/ekstra-admin', 'EkstraController');

            Route::get('/deskripsi-ekstra-admin/{desk}/edit', 'DeskripsiEkstraController@edit')->name('desk.edit');
            Route::patch('/deskripsi-ekstra-admin/{desk}', 'DeskripsiEkstraController@update')->name('desk.update');

            Route::get('/kategoriEkstra-admin/{kategoriEkstra}/edit', 'KategoriEkstraController@edit')->name('kategoriEkstra.edit');
            Route::patch('/kategoriEkstra-admin/{kategoriEkstra}', 'KategoriEkstraController@update')->name('kategoriEkstra.update');
            Route::get('/kategoriEkstra-admin/{kategoriEkstra}/delete', 'KategoriEkstraController@destroy')->name('kategoriEkstra.delete');
            Route::resource('/kategoriEkstra-admin', 'KategoriEkstraController');

            Route::get('/kegiatanPenunjang-admin/{kegiatanPenunjang}/edit', 'KegiatanPenunjangController@edit')->name('kegiatanPenunjang.edit');
            Route::patch('/kegiatanPenunjang-admin/{kegiatanPenunjang}', 'KegiatanPenunjangController@update')->name('kegiatanPenunjang.update');
            Route::get('/kegiatanPenunjang-admin/{kegiatanPenunjang}/delete', 'KegiatanPenunjangController@destroy')->name('kegiatanPenunjang.delete');
            Route::resource('/kegiatanPenunjang-admin', 'KegiatanPenunjangController');

            Route::get('/deskripsiKegiatan-admin/{deskripsiKegiatan}/edit', 'DeskripsiKegiatanController@edit')->name('deskripsiKegiatan.edit');
            Route::patch('/deskripsiKegiatan-admin/{deskripsiKegiatan}', 'DeskripsiKegiatanController@update')->name('deskripsiKegiatan.update');

            Route::get('/deskripsiBeasiswa-admin/{deskripsiBeasiswa}/edit', 'DeskripsiBeasiswaController@edit')->name('deskripsiBeasiswa.edit');
            Route::patch('/deskripsiBeasiswa-admin/{deskripsiBeasiswa}', 'DeskripsiBeasiswaController@update')->name('deskripsiBeasiswa.update');

            Route::get('/beranda-admin', 'HomeController@admin')->name('beranda.index');
            Route::get('/beranda-admin/{beranda}/edit', 'HomeController@edit')->name('beranda.edit');
            Route::patch('/beranda-admin/{beranda}', 'HomeController@update')->name('beranda.update');

            Route::get('/ppdb-admin', 'PPDBController@index')->name('ppdb.index');
            Route::get('/ppdb-admin/{ppdb}/edit', 'PPDBController@edit')->name('ppdb.edit');
            Route::patch('/ppdb-admin/{ppdb}', 'PPDBController@update')->name('ppdb.update');

            Route::get('/daftar/{daftar}/delete', 'DaftarController@destroy')->name('daftar.delete');
    });
});

routes/web.php
<?php

use Illuminate\Support\Facades\Route;

Auth::routes();
Route::redirect('/admin', '/admin/dashboard');

// Route::get('/', 'HomeController@index')->name('welcome');

require('frontend.php');

app/Alumni.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Alumni extends Model
{
    protected $fillable = [
        'nama',
        'status',
        'testimoni',
        'image',
    ];
}

app/Http/Controllers/Frontend/AlumniController.php
<?php

namespace App\Http\Controllers\Frontend;

use Illuminate\Http\Request;
use App\Http\Controllers\Controller;
use Illuminate\Support\Facades\Auth;
use Illuminate\Support\Facades\Validator;
use Illuminate\Support\Facades\Storage;
use RealRashid\SweetAlert\Facades\Alert;
use Illuminate\Support\Facades\DB;
use Illuminate\Support\Facades\Paginator;
use Carbon\Carbon;
use Image;
use App\Alumni;

class AlumniController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $alumni = Alumni::all();

        return view('admin.alumni.index', compact('alumni'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        return view('admin.alumni.create');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        Alert::success('Success', 'Data alumni berhasil ditambah');

        // $image = $request->file('image');
        // $filename = $image->getClientOriginalName();
        // $image_resize = Image::make($image->getRealPath());
        // $image_resize->resize(300, 300);
        // $image_resize->save(public_path('storage/alumni/'.$filename));

        Alumni::create([
            'nama' => request('nama'),
            'status' => request('status'),
            'testimoni' => request('testimoni'),
            'image' => request('image')->store('alumni')
        ]);

        return redirect()->route('frontend.alumni-admin.index');
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit(Alumni $alumni)
    {
        return view('admin.alumni.edit', compact('alumni'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, Alumni $alumni)
    {
        Alert::success('Success', 'Data alumni berhasil diperbarui');

        if($alumni->image){
            \Storage::delete($alumni->image);
        }

        // $image = $request->file('image');
        // $filename = $image->getClientOriginalName();
        // $image_resize = Image::make($image->getRealPath());
        // $image_resize->resize(500, 350);
        // $image_resize->save(public_path('storage/alumni/'.$filename));

        $alumni->update([
            'nama' => request('nama'),
            'status' => request('status'),
            'testimoni' => request('testimoni'),
            'image' => request('image')->store('alumni')
        ]);

        return redirect()->route('frontend.alumni-admin.index');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy(Alumni $alumni)
    {
        $alumni->delete();
        if($alumni->image){
            \Storage::delete($alumni->image);
        }
        
        return reditrect()->back();
    }
}

resources/views/admin/alumni/create.blade.php
@extends('admin.layouts')

@section('content-admin')

<div class="container-fluid">

    <div class="card">
        <div class="card-body">
            <form action="{{ route('frontend.alumni-admin.store') }}" method="post" enctype="multipart/form-data">
                {{ csrf_field() }}

                <div class="form-group">
                    <label for="">Nama</label>
                    <input type="text" class="form-control" name="nama" placeholder="Nama Lengkap">
                </div>

                <div class="form-group">
                    <label for="">Status pekerjaan/sekolah</label>
                    <input type="text" class="form-control" name="status" placeholder="Status pekerjaan/sekolah">
                </div>

                <div class="form-group">
                    <label for="">Testimoni</label>
                    <textarea class="form-control" name="testimoni" rows="3"></textarea>
                </div>

                <div class="form-group">
                    <label for="">Foto Alumni</label>
                    <input type="file" class="form-control-file" required name="image" id="">
                </div>

                <div class="form-group">
                    <button class="btn btn-primary float-right" type="submit" value="save">Tambah</button>
                </div>
            </form>
        </div>
    </div>

</div>

@endsection

resources/views/admin/alumni/edit.blade.php
@extends('admin.layouts')

@section('content-admin')

<div class="container-fluid">

    <div class="card">
        <div class="card-body">
            <form action="{{ route('frontend.alumni.update', $alumni) }}" method="post" enctype="multipart/form-data">
                {{ csrf_field() }}
                {{ method_field('PATCH') }}

                <div class="form-group">
                    <label for="">Nama</label>
                    <input type="text" class="form-control" name="nama" value="{{ $alumni->nama }}">
                </div>

                <div class="form-group">
                    <label for="">Status pekerjaan/sekolah</label>
                    <input type="text" class="form-control" name="status" value="{{ $alumni->status }}">
                </div>

                <div class="form-group">
                    <label for="">Testimoni</label>
                    <textarea class="form-control" name="testimoni" rows="3">{{ $alumni->testimoni }}</textarea>
                </div>

                <div class="form-group">
                    <label for="">Foto Alumni</label>
                    <input type="file" class="form-control-file" required name="image" value="{{ $alumni->image }}">
                </div>

                <div class="form-group">
                    <button class="btn btn-primary float-right" type="submit" value="save">Tambah</button>
                </div>
            </form>
        </div>
    </div>

</div>

@endsection

resources/views/admin/alumni/index.blade.php
@extends('admin.layouts')

@section('content-admin')

    <div class="container-fluid">

        <!-- Page Heading -->
        <div class="d-sm-flex align-items-center justify-content-between mb-4">
            <h1 class="h3 mb-0 text-gray-800">Data Alumni</h1>
             <a href="{{ route('frontend.alumni-admin.create') }}" class="d-none d-sm-inline-block btn btn-sm btn-primary shadow-sm"><i class="fas fa-plus fa-sm text-white-50"></i> Tambah Data Alumni</a> 
        </div>


        <!-- DataTales Example -->
        <div class="card shadow mb-4">
            <div class="card-header py-3">
                <h6 class="m-0 font-weight-bold text-primary">Data Alumni</h6>
            </div>
            <div class="card-body">
                <div class="table-responsive">
                    <table class="table table-bordered" id="tableAlumni">
                        <thead>
                            <tr>
                                <th>Nama</th>
                                <th>Status</th>
                                <th>Testimoni</th>
                                <th>Image</th>
                                <th>Actions</th>
                            </tr>
                        </thead>
                        <tfoot>
                            <tr>
                                <th>Nama</th>
                                <th>Status</th>
                                <th>Testimoni</th>
                                <th>Image</th>
                                <th>Actions</th>
                            </tr>
                        </tfoot>
                        <tbody>
                            @foreach ($alumni as $alm)
                                <tr>
                                    <td>{{ $alm->nama }}</td>
                                    <td>{{ $alm->status }}</td>
                                    <td>{{ $alm->testimoni }}</td>
                                    <td align="center">
                                        <img src="{{ asset('storage/' . $alm->image) }}" height="90px">
                                    </td>
                                    <td>
                                        <a href="{{ route('frontend.alumni.edit', $alm) }}"
                                            class="btn btn-primary">Edit</a>

                                        <a href="{{ route('frontend.alumni.delete', $alm->id) }}"
                                            class="btn btn-danger">Delete</a>

                                    </td>
                                </tr>
                            @endforeach

                        </tbody>
                    </table>
                </div>
            </div>
        </div>
    @endsection

    @push('script')

        <script>
            $(document).ready(function() {
                $('#tableAlumni').DataTable();
            });

        </script>

    @endpush